apiVersion: apps/v1
kind: Deployment 
metadata:
  name: karen-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: karen-api
template:
  metadata: 
    labels:
      app: karen-api 
  spec:
    containers:
      - name: karen-api
      image: us-west4-docker.pkg.dev/my-project-1st-416402/karen-api
      ports:
        - containerPort: 3000 
      resources:
        limits:
        cpu: ".5"
        memory: "500Mi" 
      requests:
        cpu: ".25"
        memory: "250Mi"
      livenessProbe:
        httpGet:
          path: / 
          port: 3000
          scheme: HTTP
        failureThreshold: 1
        periodSeconds: 10
        timeoutSeconds: 10 
      startupProbe: 
        httpGet:
          path: / 
          port: 3000
          scheme: HTTPax
        failureThreshold: 30
        periodSeconds: 10
        timeoutSeconds: 10